[[CURRENCIES]]
code="AIRLIE"
issuer="GDOW56GS47XLRDMJ4KPPAMRU6IZ57BIG5M26XMXIKFC7VY7D6TYBWSDR"
name="Airlie Reef Token"
desc="Community-driven conservation asset supporting reef protection and community rewards."
image="https://ntkleme.github.io/airlie.png"
